name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 소스 코드 Checkout
        uses: actions/checkout@v2

      - name: Node.js 설치
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 종속성 설치
        run: npm ci

      - name: Lint 체크
        run: npm run lint

      - name: e2e 테스트 실행
        run: npm run test:e2e
        env:
          AUTH_JWT_SECRET: ${{ secrets.AUTH_JWT_SECRET }}
          AUTH_JWT_TOKEN_EXPIRES_IN: ${{ secrets.AUTH_JWT_TOKEN_EXPIRES_IN }}
          AUTH_REFRESH_SECRET: ${{ secrets.AUTH_REFRESH_SECRET }}
          AUTH_REFRESH_TOKEN_EXPIRES_IN: ${{ secrets.AUTH_REFRESH_TOKEN_EXPIRES_IN }}
          AUTH_CONFIRM_EMAIL_SECRET: ${{ secrets.AUTH_CONFIRM_EMAIL_SECRET }}
          AUTH_EMAIL_TOKEN_EXPIRES_IN: ${{ secrets.AUTH_EMAIL_TOKEN_EXPIRES_IN }}
