name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
    - name: 소스 코드 Checkout  
      uses: actions/checkout@v2  

    - name: Node.js 설치
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # 사용할 Node.js 버전

    - name: 종속성 설치
      run: npm i

    - name: 유닛 테스트 실행
      run: npm run test:e2e
